TOTAL_UNIQUE_TITLES_IN_MASTER: 0
TOTAL_BOOKS_IN_MASTER: 0
TOTAL_BOOKS_IN_MASTER_FOR_PLACEMENT: 0
TOTAL_VALUE_OF_SINGLE_UNIQUE_TITLES: 0
DEFAULT_SPREADSHEET_OUT: books_spreadsheet_out.xlsx
DEFAULT_MASTER_SPREADSHEET: master_fantasy_book_list.xlsx